name: Deploy Static Website to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Create static website files
      run: |
        mkdir -p static-site
        cat > static-site/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <title>Restaurant Web</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 0; padding: 0; }
                header { background-color: #4a5568; color: white; padding: 20px; text-align: center; }
                .container { max-width: 1200px; margin: 0 auto; padding: 20px; }
                .menu-item { border: 1px solid #e2e8f0; padding: 15px; margin-bottom: 15px; border-radius: 5px; }
                .menu-item h3 { margin-top: 0; }
            </style>
        </head>
        <body>
            <header>
                <h1>Welcome to Our Restaurant</h1>
            </header>
            <div class="container">
                <h2>Our Menu</h2>
                <div class="menu-item">
                    <h3>Steak</h3>
                    <p>Delicious grilled steak with vegetables</p>
                    <p>$25.99</p>
                </div>
                <div class="menu-item">
                    <h3>Pasta</h3>
                    <p>Homemade pasta with tomato sauce</p>
                    <p>$18.99</p>
                </div>
                <div class="menu-item">
                    <h3>Salad</h3>
                    <p>Fresh garden salad with vinaigrette</p>
                    <p>$12.99</p>
                </div>
            </div>
        </body>
        </html>
        EOF
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'restaurantweb-hsowda'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: static-site
